# Generated by Django 3.1.3 on 2020-11-27 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('latitude', models.DecimalField(decimal_places=4, max_digits=20)),
                ('longitude', models.DecimalField(decimal_places=4, max_digits=20)),
                ('state', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PollutionData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('typeid', models.IntegerField()),
                ('so2', models.DecimalField(decimal_places=4, max_digits=20)),
                ('no2', models.DecimalField(decimal_places=4, max_digits=20)),
                ('pm10', models.DecimalField(decimal_places=4, max_digits=20)),
                ('co', models.DecimalField(decimal_places=4, max_digits=20)),
                ('o3_8', models.DecimalField(decimal_places=4, max_digits=20)),
                ('pm25', models.DecimalField(decimal_places=4, max_digits=20)),
                ('receptor', models.CharField(max_length=30)),
                ('wind_direction', models.IntegerField()),
                ('wind_speed', models.DecimalField(decimal_places=2, max_digits=20)),
                ('humidity', models.DecimalField(decimal_places=2, max_digits=20)),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=20)),
                ('date', models.DateField(auto_now=True, null=True)),
                ('city', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('engine_family', models.CharField(max_length=100)),
                ('manufacturer', models.CharField(max_length=100)),
                ('engine_code', models.CharField(max_length=30)),
                ('engine_model', models.CharField(max_length=30)),
            ],
        ),
    ]
