# Generated by Django 3.1.3 on 2020-11-27 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pollution', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pollutiondata',
            name='city',
        ),
    ]
