# Generated by Django 3.1.3 on 2020-11-27 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pollution', '0002_remove_pollutiondata_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollutiondata',
            name='city',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
