# Generated by Django 3.1.3 on 2020-11-27 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pollution', '0003_pollutiondata_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollutiondata',
            name='date',
            field=models.IntegerField(default=2000),
            preserve_default=False,
        ),
    ]
